### ISSUE TITLE
Default "Save into" backup location [Minor]

### ISSUE THREAD

**Issue by sum01** [whphhg/vcash-electron#11]
The default backup location is set to `~/.Vcash/data/` on install, and while I know it can be changed, I think it would make sense to have it saving into `~/.Vcash/data/backups/`

Not a big deal, just thought I'd mention it.

**Comment by whphhg** [comment]
Noted and will be corrected soon. 👍

**Comment by whphhg** [comment]
I've pushed a fix in 433da57554fceadbd626a5e12e342dc19efb6ec0.
