### ISSUE TITLE
Depreciated deps

### ISSUE THREAD

**Issue by sum01** [whphhg/vcash-electron#18]
`jade` renamed to `pug`
`transformers` renamed to `jstransformer`

```shell
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by whphhg** [comment]
Those two are from upstream dependencies that will get fixed when they upgrade their dependencies. If you check `package.json` you'll see we're not installing those packages by ourselves or they'd have been updated.
