### ISSUE TITLE
React internal inconsistencies

### ISSUE THREAD

**Issue by haiqu** [whphhg/vcash-electron#3]
I'm getting errors during install related to the React package. The build tree shows UNMET PEER DEPENDENCY react@^15.3.2 in two places and parts of the program don't seem to be working even though it does build and start.

Attempts at manual installation got this response:

C:\Users\Rob\vcash-electron>npm install react@^15.3.2
vcash-electron@0.3.1 C:\Users\Rob\vcash-electron
`-- react@15.3.2  invalid

C:\Users\Rob\vcash-electron>npm install react
vcash-electron@0.3.1 C:\Users\Rob\vcash-electron
`-- react@15.3.1

Might be wise to only require 15.3.1 for now?

**Comment by whphhg** [comment]
Noted. I haven't tested the ui-port branch on windows yet as I'm breaking things all-around in it so there will be issues until merged into master.
