### ISSUE TITLE
Unhidden Password Field

### ISSUE THREAD

**Issue by sharraf** [whphhg/vcash-electron#31]
- [X ] I have read README.md

- [X ] I have tried with the latest version and I still can reproduce the issue.

##### Vcash-electron version/branch+revision: #####
0.33.1

##### Operating system and version: #####
Ubuntu 17.04

##### Expected behavior: #####
Password field for encrypting wallet in settings should hide the clear-text entry.

##### Actual behavior: #####
Password box shows clear-text when encrypting wallet in settings.

##### Steps to reproduce the behavior: #####
Encrypt wallet in settings.

**Comment by whphhg** [comment]
Thank you! I've set `type="password"` to both inputs in `WalletEncrypt`, and to the three inputs in `WalletPassphraseChange`.

The changes will be reflected in an upcoming (soon) push to `dev` branch.

**Comment by sharraf** [comment]
wow thanks for the quick fix!!
