### ISSUE TITLE
How to check the mining reward price?

### ISSUE THREAD

**Issue by JafferWilson** [whphhg/vcash-electron#37]
I am not able to see any earning even after mining for a complete day. I don't know what is the problem as there is no error. I just see the blank stats and no earning stats are available.

Kindly, let me know how I can check the real time Vcash earning through the electron app or if it is available where I can see it or when I can see it?

**Comment by salincakli** [comment]
Assuming you use the pool.vchain.info, it has no balance check build in. It is also not working at moment, there are several complaints about no payout.

**Comment by JafferWilson** [comment]
Yes, I too haven't got anything yet.... I am still waiting. Kindly check what might be the issue... please and reward the mining revenue to me

**Comment by vcash-project** [comment]
This issue is not related to vcash-electron. Contact the mining pool this pertains to if you are having an issue there.

**Comment by Alexandr046** [comment]
Добрый день ! 
Я тоже хочу добывать монету Vcash, но я не нашел не одного рабочего pool. Единственный рабочий Vcash.info, но на нем похоже все замерло в 2016 году !  Я не знаю где можно узнать - Vcash работает ? ее можно добывать ? Она торгуется на бирже bittrex, но не известно, как ее добыть ( . Спасибо за ответ !
